<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="selenium" failures="1" tests="5" name="com.ejemplo.selenium.TesttNGBBDD" time="8.566" errors="0" timestamp="3 Oct 2025 08:21:58 GMT">
  <testcase classname="com.ejemplo.selenium.TesttNGBBDD" name="testAlgo" time="1.728">
    <failure message="expected [2.4] but found [2]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [2.4] but found [2]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.ejemplo.selenium.TesttNGBBDD.testAlgo(TesttNGBBDD.java:49)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testAlgo -->
  <testcase classname="com.ejemplo.selenium.TesttNGBBDD" name="testAlgo" time="1.613"/>
  <testcase classname="com.ejemplo.selenium.TesttNGBBDD" name="testAlgo" time="1.536"/>
  <testcase classname="com.ejemplo.selenium.TesttNGBBDD" name="testAlgo" time="2.033"/>
  <testcase classname="com.ejemplo.selenium.TesttNGBBDD" name="testAlgo" time="1.656"/>
</testsuite> <!-- com.ejemplo.selenium.TesttNGBBDD -->
